version: '3.0'

services:
  backend:
    image: 'overlinks-be'
    build: .
    ports:
      - '3005:3000'
    environment:
      - 'CFG_LOG_DEBUG=false'
    volumes:
      - '/mnt/cache/SSD/overLinks/data:/data'
  frontend:
    image: 'overlinks-fe'
    build: .
    ports:
      - '5173:80'
  telegram:
    image: 'overlinks-tg'
    build: .
    environment:
      - 'BOT_TOKEN=5882487778:AAHjTFNBfy0wtGvcJg18M9EHECYwG8xig5E'
      - 'APP_URL=https://overlinks.marcorealacci.me'
      - 'API_URL=https://overlinks.marcorealacci.me/api'